let PDFDocument, rgb, StandardFonts;

function getLibraries(){
  if(!window.XLSX) throw new Error('Library Excel belum termuat. Periksa koneksi internet atau CDN SheetJS.');
  if(!window.PDFLib) throw new Error('Library PDF belum termuat. Periksa koneksi internet atau CDN pdf-lib.');
  if(!window.JSZip) throw new Error('Library ZIP belum termuat. Periksa koneksi internet atau CDN JSZip.');
  ({PDFDocument, rgb, StandardFonts}=window.PDFLib);
  initPdfColors();
}

const state={type:'glow',level:'lower',workbook:null,students:[],photos:new Map(),manualPhotos:new Map(),selected:null,generated:new Map()};

const TEMPLATES={
  glowLower:'assets/templates/Rapor Glow Lower.pdf',
  glowMiddle:'assets/templates/Rapor Glow Middle Template.pdf',
  glowUpper:'assets/templates/Rapor Glow Upper.pdf',
  sunny:'assets/templates/Rapor Sunny Template.pdf',
  infant:'assets/templates/Rapor Infant Template.pdf'
};

const COLORS={orange:null,black:null,white:null};
function initPdfColors(){const c=window.PDFLib.rgb;COLORS.orange=c(1,.60,0);COLORS.black=c(.07,.08,.10);COLORS.white=c(1,1,1);}

const COMMON_FIELDS={name:'Nama Anak',displayName:'Nama Anak (Nilai)',gender:'Jenis Kelamin',place:'Tempat',birth:'Tanggal Lahir',father:'Nama Ayah',mother:'Nama Ibu',job:'Pekerjaan',address:'Alamat',phone:'No Telp',note:'Catatan',teacher:'Nama Guru'};

const IDENTITY_BOXES=[
  ['name',224.1,363.4,343.8,26.6],['gender',224.1,416.5,343.8,26.6],['place',224.1,469.7,343.8,26.6],['birth',224.1,522.8,343.8,26.6],
  ['father',224.1,575.9,343.8,26.6],['mother',224.1,629.1,343.8,26.6],['job',224.1,682.2,343.8,26.6],['address',224.1,735.3,343.8,26.6],['phone',224.1,788.5,343.8,26.6]
];

const CONFIG={
  lower:{sheet:'LOWER',key:'glowLower',fields:COMMON_FIELDS,results:[
    ['Perawatan Diri Sendiri',2,{x:201.6,y:365.1,w:90.7,h:16.9}],['Perawatan Lingkungan',2,{x:201.6,y:397.9,w:90.7,h:16.9}],['Perkembangan Psikomotorik',2,{x:201.6,y:430.7,w:90.7,h:36.3}],['Sikap',2,{x:201.6,y:482.9,w:90.1,h:16.1}],
    ['Perkembangan Visual',2,{x:201.6,y:570,w:90.1,h:16.9}],['Pengembangan Auditori',2,{x:201.6,y:602.8,w:90.1,h:15.6}],['Pengembangan Gustatori',2,{x:201.6,y:634.3,w:90.1,h:31.2}],['Pengembangan Olfactory',2,{x:201.6,y:681.4,w:90.1,h:31.2}],['Pengembangan Indra Peraba',2,{x:201.6,y:728.5,w:90.1,h:31.2}],
    ['Studi Alam',2,{x:490.2,y:363.5,w:91.6,h:15.9}],['Pengenalan dunia hewan',2,{x:490.2,y:395.3,w:91.6,h:16.9}],['Pengenalan dunia tumbuhan',2,{x:490.2,y:428.1,w:91.6,h:24.7}],['Pengenalan Sejarah',2,{x:490.2,y:471.3,w:91.6,h:24.7}],['Interaksi sosial',2,{x:487.7,y:584.3,w:91.6,h:15.9}],['Emosional',2,{x:487.7,y:616,w:91.6,h:18.8}],
    ['Komunikasi dua arah',3,{x:201.6,y:373.3,w:90.1,h:19.6}],['Gerak & Lagu',3,{x:201.6,y:408.8,w:90.1,h:21.1}],['Pengembangan kosakata',3,{x:201.6,y:445.8,w:90.1,h:21.7}],['Penguasaan fonetik',3,{x:201.6,y:483.3,w:90.1,h:19.7}],['Persiapan menulis',3,{x:201.6,y:518.9,w:90.1,h:21.9}],
    ['Pengenalan pola & bentuk',3,{x:492.8,y:373.3,w:90.1,h:19.6}],['Pengenalan kuantitas 1 - 10',3,{x:492.8,y:408.8,w:90.1,h:20.1}],['Pengenalan simbol 1 -10',3,{x:492.8,y:444.8,w:90.1,h:23.4}]
  ]},
  middle:{sheet:'MIDDLE',key:'glowMiddle',fields:COMMON_FIELDS,results:[
    ['Perawatan Diri Sendiri',2,{x:201.6,y:365.1,w:90.7,h:15.9}],['Perawatan Lingkungan',2,{x:201.6,y:396.8,w:90.7,h:15.9}],['Perkembangan Psikomotorik',2,{x:201.6,y:428.6,w:90.7,h:36.3}],['Sikap',2,{x:201.6,y:480.4,w:90.7,h:16.1}],
    ['Perkembangan Visual',2,{x:201.6,y:565.2,w:90.1,h:15.9}],['Pengembangan Auditori',2,{x:201.6,y:597,w:90.1,h:15.9}],['Pengembangan Gustatori',2,{x:201.6,y:628.8,w:90.1,h:31.2}],['Pengembangan Olfactory',2,{x:201.6,y:675.4,w:90.1,h:31.2}],['Pengembangan Indra Peraba',2,{x:201.6,y:722,w:90.1,h:31.2}],
    ['Studi Alam',2,{x:490.2,y:363.5,w:91.6,h:15.9}],['Pengenalan dunia hewan',2,{x:490.2,y:395.3,w:91.6,h:15.9}],['Pengenalan dunia tumbuhan',2,{x:490.2,y:427.1,w:91.6,h:24.7}],['Pengenalan Sejarah',2,{x:490.2,y:470.3,w:91.6,h:24.6}],['Interaksi sosial',2,{x:487.7,y:584.3,w:91.6,h:15.9}],['Emosional',2,{x:487.7,y:616,w:91.6,h:18.8}],
    ['Komunikasi dua arah',3,{x:201.6,y:377.4,w:90.1,h:23.4}],['Kemampuan bercerita',3,{x:201.6,y:416.7,w:90.1,h:20.2}],['Pengembangan kosakata',3,{x:201.6,y:452.8,w:90.1,h:26.1}],['Penguasaan fonetik',3,{x:201.6,y:494.8,w:90.1,h:25.8}],['Persiapan menulis',3,{x:201.6,y:536.5,w:90.1,h:22.3}],
    ['Pengenalan nilai tempat',3,{x:492.8,y:375.4,w:90.1,h:24.8}],['Pengenalan kuantitas 11-99',3,{x:492.8,y:416.1,w:90.1,h:20.1}],['Pengenalan simbol 11 -99',3,{x:492.8,y:452.1,w:90.1,h:24.9}]
  ]},
  upper:{sheet:'UPPER',key:'glowUpper',fields:COMMON_FIELDS,results:[
    ['Perawatan Diri Sendiri',2,{x:201.6,y:365.1,w:90.7,h:15.6}],['Perawatan Lingkungan',2,{x:201.6,y:396.5,w:90.7,h:17}],['Perkembangan Psikomotorik',2,{x:201.6,y:429.4,w:90.7,h:36.3}],['Sikap',2,{x:201.6,y:481.6,w:90.7,h:16.1}],
    ['Perkembangan Visual',2,{x:201.6,y:565.2,w:90.1,h:16.9}],['Pengembangan Auditori',2,{x:201.6,y:598,w:90.1,h:15.6}],['Pengembangan Gustatori',2,{x:201.6,y:629.5,w:90.1,h:31.2}],['Pengembangan Olfactory',2,{x:201.6,y:676.6,w:90.1,h:31.2}],['Pengembangan Indra Peraba',2,{x:201.6,y:723.7,w:90.1,h:31.2}],
    ['Studi Alam',2,{x:490.2,y:363.5,w:91.6,h:15.9}],['Pengenalan dunia hewan',2,{x:490.2,y:395.3,w:91.6,h:16.9}],['Pengenalan dunia tumbuhan',2,{x:490.2,y:428.1,w:91.6,h:24.7}],['Pengenalan Sejarah',2,{x:490.2,y:471.3,w:91.6,h:24.7}],['Interaksi sosial',2,{x:487.7,y:584.3,w:91.6,h:15.9}],['Emosional',2,{x:487.7,y:616,w:91.6,h:18.8}],
    ['Pemahaman individu & respon',3,{x:201.6,y:373.3,w:90.1,h:36.4}],['Kemampuan mendengarkan & berbicara',3,{x:201.6,y:425.8,w:90.1,h:38.9}],['Pengembangan kosakata',3,{x:201.6,y:480.6,w:90.1,h:28}],['Membaca',3,{x:201.6,y:524.5,w:90.1,h:26.5}],['Menulis',3,{x:201.6,y:566.9,w:90.1,h:25.8}],
    ['Pengoperasian sistem desimal',3,{x:498,y:375,w:90.2,h:33.4}],['Pengenalan matematika abstrak',3,{x:498,y:424.3,w:90.2,h:34.5}]
  ]}
};

const SUNNY={sheet:'RAPOT SUNNY',key:'sunny',fields:{name:'Nama Anak',displayName:'Nama Anak\n(Daftar Penilaian)',gender:'Jenis Kelamin',place:'Tempat',birth:'Tanggal Lahir',father:'Nama Ayah',mother:'Nama Ibu',job:'Pekerjaan',address:'Alamat',phone:'No Telp',note:'Catatan Keseluruhan',teacher:'NAMA GURU'},results:[
  ['Psikomotorik: Keseimbangan & Kasar',2,{x:205.1,y:364.3,w:89,h:24.8}],['Psikomotorik: Halus',2,{x:205.1,y:405,w:89,h:23.6}],['Sosial Emosional :\nKesadaran Diri',2,{x:205.1,y:487.2,w:89,h:16}],['Sosial Emosional:\nInteraksi',2,{x:205.1,y:521.7,w:89,h:16.1}],['Sosial Emosional:\nEmosional',2,{x:205.1,y:553.7,w:89,h:24}],['Latihan Kecakapan Hidup:\nPerawatan Diri',2,{x:490.9,y:365.3,w:95.5,h:15.9}],['Latihan Kecakapan Hidup: \nPerawatan Lingkungan',2,{x:490.9,y:397.1,w:95.5,h:16.9}],['Latihan Kecakapan Hidup: \nKolaborasi dengan orang dewasa',2,{x:490.9,y:429.9,w:95.5,h:24.1}],
  ['Perkembangan Kognitif: \nSensorial',2,{x:490.9,y:505.8,w:90.9,h:17}],['Perkembangan Kognitif: \nPembentukan Konsep',2,{x:490.9,y:540.2,w:90.9,h:16.9}],['Perkembangan Kognitif: \nKoordinasi Mata dan Tangan',2,{x:490.9,y:574.6,w:90.9,h:22.8}],['Bahasa: \nMendengar',2,{x:203.4,y:633.6,w:90.7,h:20.4}],['Bahasa: \nMerespon',2,{x:203.4,y:672.5,w:90.7,h:19.3}],['Bahasa: \nKomunikasi Dua Arah',2,{x:203.4,y:707.7,w:90.7,h:19.9}]
]};

const INFANT={sheet:'FEB',key:'infant',fields:{name:'Nama Anak',displayName:'Nama Anak\n(Daftar Penilaian)',gender:'Jenis Kelamin',place:'Tempat',birth:'Tanggal Lahir',father:'Nama Ayah',mother:'Nama Ibu',job:'Pekerjaan',address:'Alamat',phone:'No Telp',note:'CATATAN',teacher:'NAMA GURU'},results:[
  ['Psikomotor (keseimbangan)',2,{x:397.4,y:343.9,w:169,h:18.8}],['Perkembangan kognitif (Koordinasi Mata & Tangan)',2,{x:397.8,y:471.9,w:169,h:22.3}],['Perkembangan Sensorial (Eksploral Sensorial)',2,{x:397.4,y:539.3,w:169,h:23.6}],['Sosial Emosional (kesadaran diri dan Emosi)',2,{x:397.4,y:581.2,w:169,h:23.9}],['Sosial Emosional (interaksi)',2,{x:397.8,y:646.4,w:169,h:18.4}],['Mendengar',2,{x:397.8,y:683.1,w:169,h:18.3}],['Merespon',2,{x:397.4,y:405.7,w:169,h:21.8}]
]};

const templateCache=new Map();let fonts={};let previewUrl=null;let busy=false;
const $=id=>document.getElementById(id);const clean=v=>{if(v===null||v===undefined)return '';const s=String(v).trim();return /^#(VALUE|REF|DIV\/0|N\/A|NAME|NUM|NULL)!?$/i.test(s)?'':s;};
function norm(s){return clean(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\.[^.]+$/,'').replace(/[^a-z0-9]+/g,'');}
function initial(name){return clean(name).split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?';}
function fmtDate(v){if(!v)return '';if(v instanceof Date&&!Number.isNaN(v.getTime()))return new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'long',year:'numeric'}).format(v);const s=clean(v);if(/^\d{4}-\d{2}-\d{2}$/.test(s)){const d=new Date(s+'T00:00:00');return new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'long',year:'numeric'}).format(d);}return s;}
function currentDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function showMsg(text,type='info'){const el=$('message');el.textContent=text;el.className='notice show '+type;}function clearMsg(){$('message').className='notice';$('message').textContent='';}
function safeFile(s){return clean(s).replace(/[\\/:*?"<>|]+/g,' ').replace(/\s+/g,' ').trim().slice(0,100)||'Siswa';}function escapeHtml(s){return clean(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function settings(){return{city:clean($('city').value)||'Purwokerto',date:$('reportDate').value,period:clean($('period').value),className:clean($('className').value)||({sunny:'SUNNY CLASS',infant:'INFANT CLASS'}[state.type]||'GLOW CLASS'),teacher:clean($('teacher').value),principal:clean($('principal').value)||'Michelle Juwono'};}
async function getTemplate(key){if(templateCache.has(key))return templateCache.get(key);const res=await fetch(TEMPLATES[key]);if(!res.ok)throw new Error(`Template ${key} tidak ditemukan.`);const bytes=await res.arrayBuffer();templateCache.set(key,bytes);return bytes;}
async function setupFonts(doc){
  // Font rapor: ABeeZee dari folder assets/fonts.
  // ABeeZee hanya menyediakan Regular + Italic, jadi Regular dipakai untuk seluruh isi.
  if(!window.fontkit) throw new Error('Fontkit belum termuat. Refresh halaman dan pastikan koneksi internet aktif.');
  doc.registerFontkit(window.fontkit);

  const regBytes=await fetch('assets/fonts/ABeeZee-Regular.ttf').then(r=>{
    if(!r.ok) throw new Error('ABeeZee Regular tidak ditemukan.');
    return r.arrayBuffer();
  });
  const italicBytes=await fetch('assets/fonts/ABeeZee-Italic.ttf').then(r=>{
    if(!r.ok) throw new Error('ABeeZee Italic tidak ditemukan.');
    return r.arrayBuffer();
  });

  fonts.reg=await doc.embedFont(regBytes,{subset:true});
  // Tidak menggunakan italic sebagai bold agar bentuk tulisan tetap sesuai font template.
  fonts.bold=fonts.reg;
  fonts.italic=await doc.embedFont(italicBytes,{subset:true});
}
function pdfY(page,top,h){return page.getHeight()-top-h;}
function fitSize(text,maxWidth,size,font){let fs=size;while(fs>7&&font.widthOfTextAtSize(text,fs)>maxWidth)fs-=.25;return fs;}
function drawText(page,text,x,top,w,size=12,color=COLORS.black,align='left',bold=false){text=clean(text);if(!text)return;const font=bold?fonts.bold:fonts.reg;const fs=fitSize(text,w,size,font);const width=font.widthOfTextAtSize(text,fs);let xx=x;if(align==='center')xx=x+(w-width)/2;if(align==='right')xx=x+w-width;page.drawText(text,{x:xx,y:page.getHeight()-top-fs,size:fs,font,color});}
function wrapLines(text,w,size,font){const out=[];for(const paragraph of clean(text).split(/\n/)){let line='';for(const word of paragraph.split(/\s+/)){const test=line?`${line} ${word}`:word;if(font.widthOfTextAtSize(test,size)<=w)line=test;else{if(line)out.push(line);line=word;}}if(line)out.push(line);}return out;}
function drawMultiline(page,text,x,top,w,h,size=11,color=COLORS.black,align='left',bold=false){const font=bold?fonts.bold:fonts.reg;let fs=size;let lines=wrapLines(text,w,fs,font);while(lines.length>Math.max(1,Math.floor(h/(fs*1.18)))&&fs>7){fs-=.3;lines=wrapLines(text,w,fs,font);}const lh=fs*1.18;lines.slice(0,Math.floor(h/lh)).forEach((line,i)=>drawText(page,line,x,top+i*lh,w,fs,color,align,bold));}
function writeTransparent(page,box,text,opt={}){if(!clean(text))return;if(opt.center)drawText(page,text,box.x,box.y+(box.h-(opt.size||12))/2,box.w,opt.size||12,opt.color||COLORS.black,'center',!!opt.bold);else drawMultiline(page,text,box.x+2,box.y+2,box.w-4,box.h-4,opt.size||12,opt.color||COLORS.black,opt.align||'left',!!opt.bold);}
function fillRect(page,box,color=COLORS.orange){page.drawRectangle({x:box.x,y:page.getHeight()-box.y-box.h,width:box.w,height:box.h,color,borderWidth:0});}

function photoFor(student){if(!student)return null;if(state.manualPhotos.has(student.id))return state.manualPhotos.get(student.id);const candidates=[student.name,student.displayName].map(norm).filter(Boolean);for(const c of candidates)if(state.photos.has(c))return state.photos.get(c);const matches=[];for(const [key,val] of state.photos){for(const c of candidates)if(key.includes(c)||c.includes(key))matches.push({score:Math.max(key.length,c.length),val});}matches.sort((a,b)=>b.score-a.score);return matches[0]?.val||null;}
function parseRows(ws){return XLSX.utils.sheet_to_json(ws,{defval:'',raw:true});}
function getFieldValue(row,header){if(Object.prototype.hasOwnProperty.call(row,header))return row[header];const target=norm(header);const key=Object.keys(row).find(k=>norm(k)===target);return key?row[key]:'';}
function findWorksheet(cfg){const direct=state.workbook.Sheets[cfg.sheet];if(direct)return direct;const wanted=Object.values(cfg.fields).slice(0,10).map(norm);let best=null,bestScore=-1;for(const name of state.workbook.SheetNames){const ws=state.workbook.Sheets[name];const rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:true});const header=(rows[0]||[]).map(norm);const score=wanted.filter(x=>x&&header.includes(x)).length;if(score>bestScore){bestScore=score;best=ws;}}if(bestScore>=2)return best;return null;}
function parseWorkbook(){if(!state.workbook)return;if(!window.XLSX){showMsg('Library Excel belum termuat.','error');return;}const cfg=state.type==='sunny'?SUNNY:state.type==='infant'?INFANT:CONFIG[state.level];const ws=findWorksheet(cfg);if(!ws){showMsg(`Sheet data untuk ${state.type==='sunny'?'Sunny':state.type==='infant'?'Infant':state.level} tidak ditemukan.`,'error');return;}const rows=parseRows(ws);state.students=rows.filter(r=>clean(getFieldValue(r,cfg.fields.name))).map((r,index)=>{const obj={raw:r,index,id:`${state.type}-${state.level}-${index}`};for(const [k,h] of Object.entries(cfg.fields))obj[k]=getFieldValue(r,h);obj.name=clean(obj.name);obj.displayName=clean(obj.displayName);obj.note=clean(obj.note);obj.teacher=clean(obj.teacher);return obj;});state.selected=state.students[0]||null;state.generated.clear();state.manualPhotos.clear();$('downloadZipBtn').disabled=true;updateUI();}
async function loadExcel(file){clearMsg();if(!window.XLSX){showMsg('Library Excel belum termuat. Refresh halaman dan pastikan internet aktif saat pertama membuka website.','error');return;}$('excelInfo').textContent=`Membaca ${file.name}…`;try{const buf=await file.arrayBuffer();state.workbook=XLSX.read(buf,{type:'array',cellDates:true});parseWorkbook();$('excelInfo').textContent=`✓ ${file.name}`;$('excelInfo').classList.add('ok');}catch(err){console.error(err);showMsg('Excel gagal dibaca. Pastikan file .xlsx/.xls yang valid.','error');}}
function loadPhotos(files){state.photos.clear();for(const f of files){if(!f.type.startsWith('image/'))continue;const key=norm(f.name);if(key)state.photos.set(key,{file:f,url:URL.createObjectURL(f)});}$('photoInfo').textContent=files.length?`✓ ${files.length} foto siap dicocokkan`:'Belum ada foto.';$('photoInfo').classList.toggle('ok',!!files.length);if(state.students.length)updateUI();}
function updateUI(){if(!state.students.length){$('emptyState').style.display='grid';$('result').classList.remove('show');$('generateBtn').disabled=true;return;}$('emptyState').style.display='none';$('result').classList.add('show');$('generateBtn').disabled=false;$('statStudents').textContent=state.students.length;$('statPhotos').textContent=state.students.filter(s=>photoFor(s)).length;$('statTemplate').textContent=state.type==='sunny'?'Sunny':state.type==='infant'?'Infant':`Glow ${state.level[0].toUpperCase()+state.level.slice(1)}`;$('studentCount').textContent=`${state.students.length} siswa`;renderStudents();if(state.selected)selectStudent(state.selected,false);}
function renderStudents(){const list=$('studentList');list.innerHTML='';for(const s of state.students){const p=photoFor(s);const b=document.createElement('button');b.className='student'+(state.selected===s?' active':'');b.type='button';b.innerHTML=`<span class="avatar">${p?`<img src="${p.url}" alt="">`:initial(s.name)}</span><span class="student-info"><b>${escapeHtml(s.name)}</b><small>${state.type==='sunny'?'SUNNY':state.type==='infant'?'INFANT':state.level.toUpperCase()}</small></span><span class="student-status ${p?'ok':''}">${p?'✓':'○'}</span><span class="student-photo" title="Tambah/ganti foto">📷</span>`;b.onclick=()=>selectStudent(s,true);b.querySelector('.student-photo').onclick=e=>{e.stopPropagation();chooseManualPhoto(s);};list.appendChild(b);}}
function chooseManualPhoto(student){if(!student)return;state.selected=student;renderStudents();$('manualPhotoInput').value='';$('manualPhotoInput').click();}
function setPreview(blob,student){if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null;}previewUrl=URL.createObjectURL(blob);const frame=$('previewFrame');frame.innerHTML=`<object data="${previewUrl}#page=1&zoom=page-width" type="application/pdf" aria-label="Preview rapor"><div class="preview-fallback">Preview PDF tidak tampil di browser ini. <a href="${previewUrl}" target="_blank" rel="noopener">Buka PDF</a></div></object>`;$('previewMeta').textContent=photoFor(student)?'Foto ditemukan.':'Foto belum ditemukan — klik 📷 untuk menambahkan.';}
async function refreshPreview(student){$('previewTitle').textContent=student.name;$('previewMeta').textContent='Membuat preview…';$('manualPhotoBtn').disabled=false;$('downloadOneBtn').disabled=true;try{const blob=await generatePdf(student);setPreview(blob,student);state.generated.set(student.id,blob);$('downloadOneBtn').disabled=false;}catch(err){console.error(err);$('previewMeta').textContent='PDF belum bisa dibuat';showMsg(err.message||'Gagal membuat PDF.','error');}}
function selectStudent(student,rerender=true){state.selected=student;if(rerender)renderStudents();refreshPreview(student);}

function drawIdentity(page,student){const vals={name:student.name,gender:student.gender,place:student.place,birth:fmtDate(student.birth),father:student.father,mother:student.mother,job:student.job,address:student.address,phone:student.phone};for(const [key,x,y,w,h] of IDENTITY_BOXES)writeTransparent(page,{x,y,w,h},vals[key],{size:12});}
function drawHeader(page,student,set){const name=clean(student.displayName)||student.name;const infant=state.type==='infant';const bars=[{x:312.3,y:235,w:infant?255:269.5,h:infant?23.3:20.6,label:'NAMA',value:name},{x:312.3,y:262.3,w:infant?255:269.5,h:infant?22.2:20.6,label:'PERIODE / TA',value:set.period},{x:312.3,y:289.6,w:infant?255:269.5,h:infant?21.5:20.6,label:'KELAS',value:set.className},{x:397.4,y:205.5,w:infant?169.8:185.6,h:infant?19.2:18.7,label:'CABANG',value:set.city}];for(const b of bars){fillRect(page,b);drawText(page,b.label,b.x+3,b.y+3,110,12,COLORS.white,'left',true);drawText(page,':',b.x+(b.label==='CABANG'?58:112),b.y+3,12,12,COLORS.white,'left',true);const vx=b.x+(b.label==='CABANG'?66:118);drawText(page,b.value,vx,b.y+3,b.w-(vx-b.x)-5,12,COLORS.white,'left',true);}}
async function drawPhoto(page,photo,doc){if(!photo)return;const bytes=new Uint8Array(await photo.file.arrayBuffer());let img;try{img=await doc.embedJpg(bytes);}catch{try{img=await doc.embedPng(bytes);}catch{const png=await imageFileToPng(photo.file);img=await doc.embedPng(png);}}const box={x:146.6,y:218.9,w:61.1,h:84};const scale=Math.min(box.w/img.width,box.h/img.height);const w=img.width*scale,h=img.height*scale;page.drawImage(img,{x:box.x+(box.w-w)/2,y:page.getHeight()-box.y-box.h+(box.h-h)/2,width:w,height:h});}
async function imageFileToPng(file){const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;canvas.getContext('2d').drawImage(bitmap,0,0);bitmap.close();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw new Error('Foto tidak dapat diproses. Gunakan JPG atau PNG.');return new Uint8Array(await blob.arrayBuffer());}
function noteBox(kind,pageIndex){if(kind==='infant')return {x:45.8,y:746.3,w:521.4,h:69.2};if(kind==='sunny')return {x:299.8,y:647.5,w:294.8,h:106};return {x:20,y:610,w:562,h:133};}
function signaturePositions(kind,pageIndex){
  if(kind==='infant')return {date:{x:501,y:791.3,w:64,h:18},teacher:{x:340,y:810,w:100,h:18},principal:{x:465,y:790,w:110,h:18}};
  if(kind==='sunny')return {date:{x:506,y:756.2,w:80,h:18},teacher:{x:316,y:774,w:100,h:18},principal:{x:474,y:775,w:105,h:18}};
  // Glow: nama berada tepat di bawah label, lebih ke kanan, dengan ruang tanda tangan yang cukup.
  if(pageIndex===1)return {date:{x:516,y:774.8,w:62,h:18},teacher:{x:290,y:880,w:100,h:18},principal:{x:455,y:880,w:100,h:18}};
  return {date:{x:513,y:735,w:70,h:18},teacher:{x:310,y:870,w:95,h:18},principal:{x:465,y:870,w:95,h:18}};
}

async function generatePdf(student){getLibraries();const cfg=state.type==='sunny'?SUNNY:state.type==='infant'?INFANT:CONFIG[state.level];const bytes=await getTemplate(cfg.key);const doc=await PDFDocument.load(bytes);await setupFonts(doc);const set=settings();const pages=doc.getPages();const kind=state.type==='sunny'?'sunny':state.type==='infant'?'infant':state.level;drawIdentity(pages[0],student);const photo=photoFor(student);for(let i=1;i<pages.length;i++){drawHeader(pages[i],student,set);if(i===1)await drawPhoto(pages[i],photo,doc);for(const [header,pageNo,box] of cfg.results){if(pageNo===i+1){const val=clean(getFieldValue(student.raw,header));writeTransparent(pages[i],box,val,{size:12,center:true});}}const sig=signaturePositions(kind,i);const dateText=set.date?fmtDate(set.date):'';if(dateText)drawText(pages[i],dateText,sig.date.x,sig.date.y,sig.date.w,10.5,COLORS.orange,'left',false);const teacher=clean(set.teacher)||student.teacher;if(teacher)drawText(pages[i],teacher,sig.teacher.x,sig.teacher.y,sig.teacher.w,10.5,COLORS.orange,'center',true);if(set.principal)drawText(pages[i],set.principal,sig.principal.x,sig.principal.y,sig.principal.w,10.5,COLORS.orange,'center',true);}
const note=clean(student.note);if(note){const p=pages[pages.length-1];const b=noteBox(kind,pages.length-1);writeTransparent(p,b,note,{size:10.5});}return new Blob([await doc.save()],{type:'application/pdf'});}

async function generateAll(showSuccess=true){if(!state.students.length||busy)return false;busy=true;state.generated.clear();$('progress').classList.add('show');$('generateBtn').disabled=true;$('downloadZipBtn').disabled=true;$('statStatus').textContent='Membuat…';$('progressBar').style.width='0%';$('progressPct').textContent='0%';const errors=[];try{for(let i=0;i<state.students.length;i++){const s=state.students[i];$('progressText').textContent=`Membuat ${i+1}/${state.students.length}: ${s.name}`;try{state.generated.set(s.id,await generatePdf(s));}catch(err){console.error('Gagal membuat',s.name,err);errors.push(`${s.name}: ${err.message||'gagal membuat PDF'}`);}const pct=Math.round((i+1)/state.students.length*100);$('progressBar').style.width=pct+'%';$('progressPct').textContent=pct+'%';}const ok=state.generated.size;$('progressText').textContent=errors.length?`${ok} selesai, ${errors.length} gagal.`:'Semua rapor selesai.';$('statStatus').textContent=errors.length?`${ok} berhasil`:'Selesai';$('downloadZipBtn').disabled=!ok;if(showSuccess){if(errors.length)showMsg(`${ok} rapor berhasil dibuat. ${errors.length} siswa gagal: ${errors.slice(0,3).join(' | ')}`,ok?'success':'error');else showMsg(`${ok} rapor berhasil dibuat.`,'success');}return ok>0;}finally{busy=false;$('generateBtn').disabled=false;}}
async function downloadZip(){try{getLibraries();}catch(err){showMsg(err.message,'error');return;}if(!state.students.length){showMsg('Upload Excel terlebih dahulu.','info');return;}if(state.generated.size!==state.students.length){const ok=await generateAll(false);if(!ok){showMsg('Tidak ada raport yang berhasil dibuat.','error');return;}}const zip=new JSZip();for(const s of state.students){const blob=state.generated.get(s.id);if(blob)zip.file(`${safeFile(s.name)}.pdf`,blob);}const out=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}},meta=>{const pct=Math.round(meta.percent);$('progress').classList.add('show');$('progressText').textContent='Mengemas ZIP…';$('progressPct').textContent=pct+'%';$('progressBar').style.width=pct+'%';});saveBlob(out,`Rapor_${state.type==='sunny'?'Sunny':state.type==='infant'?'Infant':`Glow_${state.level}`}_Semua.zip`);showMsg(`${state.generated.size} raport berhasil dikemas ke ZIP.`,'success');}
function saveBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1500);}

$('reportDate').value=currentDate();$('excelBtn').onclick=()=>$('excelInput').click();$('photoBtn').onclick=()=>$('photoInput').click();$('excelInput').onchange=e=>{if(e.target.files[0])loadExcel(e.target.files[0]);e.target.value='';};$('photoInput').onchange=e=>{loadPhotos([...e.target.files]);e.target.value='';};$('manualPhotoBtn').onclick=()=>{if(state.selected)chooseManualPhoto(state.selected);};$('manualPhotoInput').onchange=e=>{const f=e.target.files[0];if(!f||!state.selected)return;const old=state.manualPhotos.get(state.selected.id);if(old?.url)URL.revokeObjectURL(old.url);state.manualPhotos.set(state.selected.id,{file:f,url:URL.createObjectURL(f)});state.generated.delete(state.selected.id);$('photoInfo').textContent=`✓ Foto manual untuk ${state.selected.name}`;$('photoInfo').classList.add('ok');renderStudents();refreshPreview(state.selected);e.target.value='';};$('generateBtn').onclick=()=>generateAll(true);$('downloadZipBtn').onclick=downloadZip;$('downloadOneBtn').onclick=async()=>{if(!state.selected)return;try{const blob=state.generated.get(state.selected.id)||await generatePdf(state.selected);state.generated.set(state.selected.id,blob);saveBlob(blob,`${safeFile(state.selected.name)}.pdf`);}catch(e){showMsg(e.message||'Gagal membuat PDF.','error');}};$('resetBtn').onclick=()=>location.reload();
['city','reportDate','period','className','teacher','principal'].forEach(id=>$(id).addEventListener('input',()=>{state.generated.clear();$('downloadZipBtn').disabled=true;if(state.selected)refreshPreview(state.selected);}));
function checkLibraries(){const missing=[];if(!window.XLSX)missing.push('Excel (SheetJS)');if(!window.PDFLib)missing.push('PDF (pdf-lib)');if(!window.JSZip)missing.push('ZIP (JSZip)');if(!window.fontkit)missing.push('fontkit (font custom)');if(!window.XLSX)showMsg('Library Excel belum termuat. Refresh halaman dan pastikan internet aktif saat pertama membuka website.','error');else if(missing.length)showMsg(`Excel siap. ${missing.includes('fontkit (font custom)')?'Font custom belum termuat; PDF tetap bisa dibuat dengan font fallback. ':''}${missing.filter(x=>x!=='fontkit (font custom)').length?'Library: '+missing.filter(x=>x!=='fontkit (font custom)').join(', '):''}`,'info');}
window.addEventListener('load',()=>setTimeout(checkLibraries,50));
for(const btn of document.querySelectorAll('.type-card'))btn.onclick=()=>{document.querySelectorAll('.type-card').forEach(x=>x.classList.remove('active'));btn.classList.add('active');state.type=btn.dataset.type;$('glowLevels').classList.toggle('show',state.type==='glow');$('className').value=state.type==='sunny'?'SUNNY CLASS':state.type==='infant'?'INFANT CLASS':'GLOW CLASS';clearMsg();if(state.workbook)parseWorkbook();};
for(const btn of document.querySelectorAll('.seg button'))btn.onclick=()=>{document.querySelectorAll('.seg button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');state.level=btn.dataset.level;$('className').value='GLOW CLASS';clearMsg();if(state.workbook)parseWorkbook();};
function wireDrop(id,handler){const el=$(id);for(const ev of ['dragenter','dragover'])el.addEventListener(ev,e=>{e.preventDefault();el.classList.add('drag');});for(const ev of ['dragleave','drop'])el.addEventListener(ev,e=>{e.preventDefault();el.classList.remove('drag');});el.addEventListener('drop',e=>handler(e.dataTransfer.files));}
wireDrop('excelDrop',files=>{const f=[...files].find(x=>/\.xlsx?$|\.xlsm$/i.test(x.name));if(f)loadExcel(f);});wireDrop('photoDrop',files=>loadPhotos([...files].filter(f=>f.type.startsWith('image/'))));
